(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let tickets=[],openId='',busy=false;
const fa=()=>document.documentElement.lang==='fa'||document.documentElement.dataset.language==='fa';
const copy={en:{eyebrow:'SUPPORT',title:'Support & Tickets',intro:'Send a request and follow every reply and status here.',new:'New ticket',subject:'Subject',category:'Category',message:'Message',send:'Send ticket',cancel:'Cancel',empty:'No support tickets yet.',you:'You',admin:'LifeLingo Support',reply:'Write a reply…',sendReply:'Send reply',closed:'This ticket is closed.',loading:'Loading tickets…',sent:'Ticket sent ✓',replySent:'Reply sent ✓',error:'Could not complete this request.'},fa:{eyebrow:'پشتیبانی',title:'پشتیبانی و تیکت‌ها',intro:'درخواستت را ثبت کن و پاسخ‌ها و وضعیت آن را همین‌جا ببین.',new:'تیکت جدید',subject:'موضوع',category:'دسته‌بندی',message:'پیام',send:'ثبت تیکت',cancel:'انصراف',empty:'هنوز تیکتی ثبت نکرده‌ای.',you:'شما',admin:'پشتیبانی LifeLingo',reply:'پاسخت را بنویس…',sendReply:'ارسال پاسخ',closed:'این تیکت بسته شده است.',loading:'در حال بارگذاری تیکت‌ها…',sent:'تیکت ثبت شد ✓',replySent:'پاسخ ارسال شد ✓',error:'انجام این درخواست ممکن نشد.'}};
const t=k=>copy[fa()?'fa':'en'][k],statuses={OPEN:['Open','باز'],WAITING_FOR_ADMIN:['Waiting for support','در انتظار پشتیبانی'],WAITING_FOR_USER:['Waiting for you','در انتظار پاسخ شما'],RESOLVED:['Resolved','حل‌شده'],CLOSED:['Closed','بسته']};
const statusLabel=s=>(statuses[s]||[s,s])[fa()?1:0],statusClass=s=>s==='WAITING_FOR_ADMIN'?'waiting-admin':s==='WAITING_FOR_USER'?'waiting-user':s==='RESOLVED'?'resolved':'';
const cats=()=>fa()?['account|حساب کاربری','billing|پرداخت و اشتراک','technical|مشکل فنی','learning|یادگیری','partner|هم‌تمرینی‌ها','other|سایر']:['account|Account','billing|Billing & plan','technical|Technical issue','learning|Learning','partner|Partners','other|Other'];
const date=v=>{try{return new Date(v).toLocaleString(fa()?'fa-IR':'en-US',{dateStyle:'medium',timeStyle:'short'})}catch{return''}};
function install(){const root=$('#profileRoot');if(!root||!root.children.length||$('[data-support-card]',root))return;const card=document.createElement('article');card.className='card llSupportCard';card.dataset.supportCard='1';card.addEventListener('click',event=>event.stopPropagation());root.append(card);render();load()}
function render(){const card=$('[data-support-card]');if(!card)return;card.innerHTML=`<div class="llSupportHead"><div><div class="eyebrow">${t('eyebrow')}</div><h2>${t('title')}</h2><p class="muted">${t('intro')}</p></div><button class="primary" data-ticket-new>${t('new')}</button></div><div class="llSupportForm hidden" data-ticket-form><div class="field"><label>${t('subject')}</label><input data-ticket-subject maxlength="120"></div><div class="field"><label>${t('category')}</label><select data-ticket-category>${cats().map(x=>{const [v,l]=x.split('|');return`<option value="${v}">${l}</option>`}).join('')}</select></div><div class="field"><label>${t('message')}</label><textarea data-ticket-body maxlength="2000"></textarea></div><div class="actions"><button class="primary" data-ticket-create>${t('send')}</button><button class="ghost" data-ticket-cancel>${t('cancel')}</button></div></div><div class="llSupportFeedback" data-ticket-feedback></div><div class="llTicketList" data-ticket-list>${ticketMarkup()}</div>`}
function ticketMarkup(){if(!tickets.length)return`<div class="empty">${t('empty')}</div>`;return tickets.map(ticket=>{const open=ticket.id===openId,closed=ticket.status==='CLOSED';return`<article class="llTicket"><button class="llTicketSummary" data-ticket-open="${esc(ticket.id)}"><span class="llTicketNumber">#${esc(ticket.ticketNumber)}</span><span><b>${esc(ticket.subject)}</b><small>${date(ticket.lastMessageAt)}</small></span><span class="llTicketStatus ${statusClass(ticket.status)}">${esc(statusLabel(ticket.status))}</span></button>${open?`<div class="llTicketThread">${(ticket.messages||[]).map(m=>`<div class="llTicketMessage ${m.authorRole==='ADMIN'?'admin':''}"><small>${m.authorRole==='ADMIN'?t('admin'):t('you')} · ${date(m.createdAt)}</small><div>${esc(m.body)}</div></div>`).join('')}${closed?`<p class="muted">${t('closed')}</p>`:`<div class="llTicketReply"><textarea class="ui" data-ticket-reply-body="${esc(ticket.id)}" maxlength="2000" placeholder="${t('reply')}"></textarea><button class="primary" data-ticket-reply="${esc(ticket.id)}">${t('sendReply')}</button></div>`}</div>`:''}</article>`}).join('')}
async function load(){if(!window.llSupabase||busy)return;busy=true;const list=$('[data-ticket-list]');if(list)list.innerHTML=`<div class="loading">${t('loading')}</div>`;try{const {data,error}=await window.llSupabase.rpc('get_my_support_tickets_v1');if(error)throw error;tickets=Array.isArray(data)?data:[];if(openId&&!tickets.some(x=>x.id===openId))openId='';if(list)list.innerHTML=ticketMarkup()}catch(error){if(list)list.innerHTML=`<div class="error">${esc(error?.message||t('error'))}</div>`}finally{busy=false}}
const feedback=value=>{const el=$('[data-ticket-feedback]');if(el)el.textContent=value};
async function create(){if(busy)return;const subject=$('[data-ticket-subject]')?.value.trim(),category=$('[data-ticket-category]')?.value,body=$('[data-ticket-body]')?.value.trim();if(!subject||!body)return feedback(t('error'));busy=true;try{const {error}=await window.llSupabase.rpc('create_support_ticket_v1',{p_subject:subject,p_category:category,p_body:body});if(error)throw error;feedback(t('sent'));$('[data-ticket-form]')?.classList.add('hidden');busy=false;await load()}catch(error){feedback(error?.message||t('error'));busy=false}}
async function reply(id){if(busy)return;const body=$(`[data-ticket-reply-body="${CSS.escape(id)}"]`)?.value.trim();if(!body)return;busy=true;try{const {error}=await window.llSupabase.rpc('reply_support_ticket_v1',{p_ticket_id:id,p_body:body});if(error)throw error;feedback(t('replySent'));busy=false;await load()}catch(error){feedback(error?.message||t('error'));busy=false}}
document.addEventListener('click',event=>{const target=event.target,action=target.closest('[data-ticket-new],[data-ticket-cancel],[data-ticket-create],[data-ticket-open],[data-ticket-reply]');if(!action)return;event.preventDefault();event.stopPropagation();if(action.matches('[data-ticket-new]')){$('[data-ticket-form]')?.classList.remove('hidden');return}if(action.matches('[data-ticket-cancel]')){$('[data-ticket-form]')?.classList.add('hidden');return}if(action.matches('[data-ticket-create]')){create();return}if(action.matches('[data-ticket-open]')){openId=openId===action.dataset.ticketOpen?'':action.dataset.ticketOpen;const list=$('[data-ticket-list]');if(list)list.innerHTML=ticketMarkup();return}reply(action.dataset.ticketReply)},true);
const observer=new MutationObserver(install);observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('lifelingo:language-change',()=>{render();load()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
