(()=>{
'use strict';
const STORAGE_KEY='lifelingo_language';
const SUPPORTED=['en','fa'];
const ENGLISH_TARGET_SELECTORS=['.dailyPhrase','.wordCard h2','[data-speak]','#lessonHeading','.lessonPanel b','.lessonPanel input','.chatMessages .message-user','.chatMessages .message-partner','[data-learning-target]'];
const messages={
 en:{
  'nav.home':'Home','nav.learn':'Learn','nav.speak':'Speak','nav.partners':'Partners','nav.review':'Review','nav.profile':'Profile',
  'auth.hero':'Learn the language you will actually use.','auth.sub':'Speak through real situations, build your course journey, practice daily and connect with language partners.','auth.login':'Log in','auth.register':'Create account','auth.email':'Email','auth.password':'Password','auth.name':'Name','auth.mobile':'Mobile','auth.consent':'I agree to receive plan-related contact or introductions. Optional.','auth.connectError':'Could not connect. Refresh and try again.',
  'common.back':'Back','common.profile':'Profile','common.loading':'Loading…','common.saving':'Saving…','common.saved':'Saved ✓','common.check':'Check','common.send':'Send','common.report':'Report','common.block':'Block','common.choose':'Choose…','common.free':'Free','common.pro':'Pro','common.expired':'Expired','common.system':'System','common.dark':'Dark','common.light':'Light','common.working':'Working…',
  'section.learn':'LEARN','section.speak':'SPEAK','section.partners':'PARTNERS','section.review':'REVIEW','section.profile':'PROFILE & PASSPORT','section.pro':'LIFELINGO PRO',
  'learn.heading':'Prepare for real life.','learn.sub':'Courses give structure. Every chapter prepares you for a situation you will actually face.','learn.noCourse':'No active course yet.','learn.course':'COURSE','learn.chapter':'CHAPTER','learn.complete':'✓ COMPLETE','learn.openPath':'Open learning path','learn.preview':'Preview','learn.proJourney':'See Pro journey','learn.loadingLesson':'Loading lesson…','learn.unsupported':'Unsupported lesson type.','learn.previousFirst':'Complete the previous lesson first.',
  'speak.heading':'Use your English now.','speak.sub':'Conversation Missions and animated scenarios are a core LifeLingo experience, not an extra.','speak.featured':'FEATURED REAL-LIFE MISSION','speak.engine':'This uses LifeLingo’s existing animated mission engine and voice flow.','speak.start':'🎙 Start speaking','speak.library':'SCENARIO LIBRARY','speak.practice':'Practice the situations you care about.','speak.daily':'DAILY SPEAKING','speak.dailySub':'Use today’s phrase aloud. Daily practice is available on Free.','speak.listen':'🔊 Listen','speak.openDaily':'Open Daily Surprise','speak.now':'🎙 Speak Now','speak.enter':'Enter scenario →',
  'partners.heading':'Practice with real people.','partners.sub':'Discover compatible language partners, keep one active Partner on Free, and continue your conversations here.','partners.preferences':'Matching preferences','partners.languagePartner':'Language Partner','partners.find':'Find Partner','partners.findLong':'Find a language Partner','partners.open':'Open conversations','partners.human':'HUMAN PRACTICE','partners.free':'Free includes Partner discovery and one active direct Partner.',
  'review.heading':'Bring it back before it fades.','review.sub':'Review is built from what you have completed, not a random quiz list.','review.building':'Building your review queue…','review.none':'Nothing due right now ✓','review.noneSub':'Complete learning lessons and LifeLingo will create useful review items here.','review.continue':'Continue learning','review.answer':'Your answer','review.correct':'✓ Correct','review.notQuite':'Not quite — answer: {answer}','review.now':'Review now','review.personalized':'PERSONALIZED REVIEW','review.keepAlive':'Keep weak items alive.','review.unlimited':'Unlimited review depth','review.freeLimit':'Free review: up to {count} due items.',
  'home.journey':'YOUR REAL-LIFE JOURNEY','home.hero':'Learn it. Use it. Live it.','home.nextReady':'Your next journey is ready.','home.continue':'Continue lesson →','home.openLearn':'Open Learn →','home.dayStreak':'day streak','home.chapters':'chapters','home.passport':'LIFE PASSPORT','home.passportProgress':'Passport Level {level} · Progress through situations you can handle in real life.','home.viewPassport':'View Passport','home.speakNow':'SPEAK NOW','home.speakSub':'Step into a situation, hear the other person and answer out loud.','home.continueChapter':'CONTINUE CHAPTER','home.chapterComplete':'Chapter complete ✓','home.chapterReview':'Review or continue your journey with the next chapter.','home.recommended':'RECOMMENDED FOR YOU','home.realSituations':'Real situations based on your goals','home.goals':'YOUR GOALS','home.tellGoals':'Tell LifeLingo why you’re learning','home.goalsSub':'Recommendations and scenario order adapt to your choices. You can change them anytime.','home.editGoals':'Edit goals',
  'daily.title':'DAILY SURPRISE','daily.done':'You showed up today ✓','daily.open':'Open today’s real-life challenge','daily.free':'Free every day · speaking or typing','daily.again':'Practice again','daily.speak':'🎙 Speak today','daily.yourAnswer':'Your answer','daily.placeholder':'Speak or type the phrase…','daily.mic':'🎙 Mic','daily.complete':'Check & complete',
  'profile.title':'Your LifeLingo journey.','profile.passport':'LIFE PASSPORT','profile.learner':'LifeLingo learner','profile.addGoals':'Add learning goals','profile.edit':'Edit Profile','profile.partnerPrefs':'Partner Preferences','profile.streak':'Streak','profile.chapters':'Chapters','profile.passportLevel':'Passport Level','profile.achievements':'ACHIEVEMENTS','profile.milestones':'Your milestones','profile.earned':'Earned','profile.keepGoing':'Keep going','profile.plan':'YOUR PLAN','profile.manage':'Manage journey','profile.renew':'Renew Pro','profile.explore':'Explore Pro','profile.theme':'THEME','profile.makeYours':'Make LifeLingo yours','profile.themeSaved':'Theme preference is saved with your account.','profile.language':'LANGUAGE','profile.languageHeading':'Application language','profile.languageHelp':'Navigation and explanations change language; the English you are learning stays English.','profile.account':'ACCOUNT & PRIVACY','profile.privacy':'Partner discovery uses your language profile and age group. Your mobile number remains private and is not shown to Partners.','profile.logout':'Log out','profile.editHeading':'Edit Profile','profile.editSub':'Update your LifeLingo identity, goals and preferences without losing progress.','profile.avatarPhoto':'Avatar & profile picture','profile.avatarHelp':'Choose a LifeLingo avatar or upload your own photo.','profile.upload':'📷 Upload photo','profile.displayName':'Display name','profile.bio':'Bio','profile.native':'Native language','profile.learning':'Learning language','profile.currentLevel':'Current level','profile.targetLevel':'Target level','profile.why':'Why are you learning?','profile.scenarios':'Preferred scenarios','profile.interests':'Interests','profile.ageSafety':'Age group for Partner safety','profile.discoverable':'Allow my safe language profile to appear in Partner discovery.','profile.save':'Save Profile',
  'pro.heading':'Go further, not just past a paywall.','pro.sub':'Free shows the real product. Pro expands chapters, scenarios, review depth and Partner capacity.',
  'chat.write':'Write a message…','chat.send':'Send','chat.partner':'Partner','chat.languagePartner':'Language Partner',
  'status.syncing':'Syncing your LifeLingo world…','status.syncFailed':'Could not sync your account.','status.progressSynced':'Conversation progress synced ✓','status.languageSaved':'Language preference saved.','status.languageSaveFailed':'Language changed on this device, but account sync failed.',
  'language.english':'English','language.persian':'فارسی'
 },
 fa:{
  'nav.home':'خانه','nav.learn':'یادگیری','nav.speak':'مکالمه','nav.partners':'هم‌تمرینی‌ها','nav.review':'مرور','nav.profile':'پروفایل',
  'auth.hero':'زبانی را یاد بگیر که واقعاً استفاده‌اش می‌کنی.','auth.sub':'در موقعیت‌های واقعی صحبت کن، مسیر دوره‌ات را بساز، هر روز تمرین کن و با هم‌تمرینی‌های زبان ارتباط بگیر.','auth.login':'ورود','auth.register':'ساخت حساب','auth.email':'ایمیل','auth.password':'رمز عبور','auth.name':'نام','auth.mobile':'موبایل','auth.consent':'مایلم پیام‌های مربوط به پلن یا معرفی‌ها را دریافت کنم. اختیاری است.','auth.connectError':'اتصال برقرار نشد. صفحه را تازه‌سازی و دوباره امتحان کن.',
  'common.back':'بازگشت','common.profile':'پروفایل','common.loading':'در حال بارگذاری…','common.saving':'در حال ذخیره…','common.saved':'ذخیره شد ✓','common.check':'بررسی','common.send':'ارسال','common.report':'گزارش','common.block':'مسدودکردن','common.choose':'انتخاب کنید…','common.free':'رایگان','common.pro':'پرو','common.expired':'منقضی‌شده','common.system':'سیستم','common.dark':'تیره','common.light':'روشن','common.working':'در حال انجام…',
  'section.learn':'یادگیری','section.speak':'مکالمه','section.partners':'هم‌تمرینی‌ها','section.review':'مرور','section.profile':'پروفایل و پاسپورت','section.pro':'لایف‌لینگو پرو',
  'learn.heading':'برای زندگی واقعی آماده شو.','learn.sub':'دوره‌ها به مسیرت ساختار می‌دهند. هر فصل برای موقعیتی آماده‌ات می‌کند که واقعاً با آن روبه‌رو می‌شوی.','learn.noCourse':'هنوز دورهٔ فعالی نداری.','learn.course':'دوره','learn.chapter':'فصل','learn.complete':'✓ کامل شد','learn.openPath':'باز کردن مسیر یادگیری','learn.preview':'پیش‌نمایش','learn.proJourney':'دیدن مسیر پرو','learn.loadingLesson':'در حال بارگذاری درس…','learn.unsupported':'این نوع درس پشتیبانی نمی‌شود.','learn.previousFirst':'اول درس قبلی را کامل کن.',
  'speak.heading':'همین حالا از انگلیسی‌ات استفاده کن.','speak.sub':'ماموریت‌های مکالمه و سناریوهای متحرک بخش اصلی تجربهٔ LifeLingo هستند، نه یک قابلیت جانبی.','speak.featured':'ماموریت واقعی پیشنهادی','speak.engine':'این بخش از موتور سناریوی متحرک و جریان صوتی فعلی LifeLingo استفاده می‌کند.','speak.start':'🎙 شروع مکالمه','speak.library':'کتابخانه سناریوها','speak.practice':'موقعیت‌هایی را تمرین کن که برایت مهم‌اند.','speak.daily':'تمرین گفتاری روزانه','speak.dailySub':'عبارت امروز را با صدای بلند بگو. تمرین روزانه در پلن رایگان هم در دسترس است.','speak.listen':'🔊 گوش دادن','speak.openDaily':'باز کردن سورپرایز روزانه','speak.now':'🎙 همین حالا صحبت کن','speak.enter':'ورود به سناریو ←',
  'partners.heading':'با آدم‌های واقعی تمرین کن.','partners.sub':'هم‌تمرینی‌های سازگار را پیدا کن، در پلن رایگان یک Partner فعال داشته باش و گفت‌وگوهایت را همین‌جا ادامه بده.','partners.preferences':'تنظیمات تطبیق','partners.languagePartner':'هم‌تمرینی زبان','partners.find':'پیدا کردن Partner','partners.findLong':'پیدا کردن هم‌تمرینی زبان','partners.open':'باز کردن گفت‌وگوها','partners.human':'تمرین با آدم واقعی','partners.free':'پلن رایگان شامل جست‌وجوی Partner و یک Partner مستقیم فعال است.',
  'review.heading':'قبل از اینکه یادت برود دوباره مرورش کن.','review.sub':'مرور از چیزهایی ساخته می‌شود که تمام کرده‌ای، نه از یک فهرست آزمون تصادفی.','review.building':'در حال ساخت صف مرور…','review.none':'فعلاً چیزی برای مرور نیست ✓','review.noneSub':'درس‌ها را کامل کن تا LifeLingo موارد مفید برای مرور را اینجا بسازد.','review.continue':'ادامه یادگیری','review.answer':'پاسخ تو','review.correct':'✓ درست','review.notQuite':'هنوز نه — پاسخ: {answer}','review.now':'مرور حالا','review.personalized':'مرور شخصی‌سازی‌شده','review.keepAlive':'نقاط ضعیف را زنده نگه دار.','review.unlimited':'مرور نامحدود','review.freeLimit':'مرور رایگان: حداکثر {count} مورد آماده.',
  'home.journey':'مسیر واقعی تو','home.hero':'یاد بگیر. استفاده کن. زندگی کن.','home.nextReady':'مرحلهٔ بعدی مسیرت آماده است.','home.continue':'ادامه درس ←','home.openLearn':'باز کردن یادگیری ←','home.dayStreak':'روز پیوستگی','home.chapters':'فصل','home.passport':'پاسپورت زندگی','home.passportProgress':'سطح پاسپورت {level} · با تسلط بر موقعیت‌های واقعی پیشرفت کن.','home.viewPassport':'دیدن پاسپورت','home.speakNow':'همین حالا صحبت کن','home.speakSub':'وارد یک موقعیت شو، طرف مقابل را بشنو و با صدای بلند جواب بده.','home.continueChapter':'ادامه فصل','home.chapterComplete':'فصل کامل شد ✓','home.chapterReview':'مرور کن یا مسیرت را با فصل بعدی ادامه بده.','home.recommended':'پیشنهاد برای تو','home.realSituations':'موقعیت‌های واقعی براساس هدف‌هایت','home.goals':'هدف‌های تو','home.tellGoals':'به LifeLingo بگو چرا زبان می‌خوانی','home.goalsSub':'پیشنهادها و ترتیب سناریوها با انتخاب‌هایت هماهنگ می‌شوند. هر زمان بخواهی می‌توانی تغییرشان دهی.','home.editGoals':'ویرایش هدف‌ها',
  'daily.title':'سورپرایز روزانه','daily.done':'امروز تمرین کردی ✓','daily.open':'چالش واقعی امروز را باز کن','daily.free':'هر روز رایگان · گفتاری یا تایپی','daily.again':'تمرین دوباره','daily.speak':'🎙 تمرین امروز','daily.yourAnswer':'پاسخ تو','daily.placeholder':'عبارت را بگو یا تایپ کن…','daily.mic':'🎙 میکروفون','daily.complete':'بررسی و تکمیل',
  'profile.title':'مسیر LifeLingo تو.','profile.passport':'پاسپورت زندگی','profile.learner':'زبان‌آموز LifeLingo','profile.addGoals':'افزودن هدف یادگیری','profile.edit':'ویرایش پروفایل','profile.partnerPrefs':'تنظیمات Partner','profile.streak':'پیوستگی','profile.chapters':'فصل‌ها','profile.passportLevel':'سطح پاسپورت','profile.achievements':'دستاوردها','profile.milestones':'نقطه‌های مهم تو','profile.earned':'گرفته شد','profile.keepGoing':'ادامه بده','profile.plan':'پلن تو','profile.manage':'مدیریت مسیر','profile.renew':'تمدید پرو','profile.explore':'دیدن پرو','profile.theme':'ظاهر','profile.makeYours':'LifeLingo را مطابق سلیقه‌ات کن','profile.themeSaved':'تنظیم ظاهر همراه حسابت ذخیره می‌شود.','profile.language':'زبان','profile.languageHeading':'زبان برنامه','profile.languageHelp':'منوها و توضیحات ترجمه می‌شوند؛ انگلیسی‌ای که در حال یادگیری هستی انگلیسی باقی می‌ماند.','profile.account':'حساب و حریم خصوصی','profile.privacy':'پیدا کردن Partner از پروفایل زبانی و گروه سنی تو استفاده می‌کند. شماره موبایلت خصوصی است و به Partnerها نمایش داده نمی‌شود.','profile.logout':'خروج','profile.editHeading':'ویرایش پروفایل','profile.editSub':'هویت، هدف‌ها و تنظیمات LifeLingo را بدون از دست رفتن پیشرفت تغییر بده.','profile.avatarPhoto':'آواتار و عکس پروفایل','profile.avatarHelp':'یک آواتار LifeLingo انتخاب کن یا عکس خودت را بارگذاری کن.','profile.upload':'📷 بارگذاری عکس','profile.displayName':'نام نمایشی','profile.bio':'درباره من','profile.native':'زبان مادری','profile.learning':'زبان در حال یادگیری','profile.currentLevel':'سطح فعلی','profile.targetLevel':'سطح هدف','profile.why':'چرا زبان یاد می‌گیری؟','profile.scenarios':'سناریوهای ترجیحی','profile.interests':'علایق','profile.ageSafety':'گروه سنی برای ایمنی Partner','profile.discoverable':'پروفایل زبانی امن من در جست‌وجوی Partner نمایش داده شود.','profile.save':'ذخیره پروفایل',
  'pro.heading':'فراتر برو، نه فقط پشت یک دیوار پرداخت.','pro.sub':'پلن رایگان محصول واقعی را نشان می‌دهد. پرو فصل‌ها، سناریوها، عمق مرور و ظرفیت Partner را بیشتر می‌کند.',
  'chat.write':'پیام بنویس…','chat.send':'ارسال','chat.partner':'Partner','chat.languagePartner':'هم‌تمرینی زبان',
  'status.syncing':'در حال همگام‌سازی دنیای LifeLingo…','status.syncFailed':'همگام‌سازی حساب انجام نشد.','status.progressSynced':'پیشرفت مکالمه همگام شد ✓','status.languageSaved':'زبان برنامه ذخیره شد.','status.languageSaveFailed':'زبان روی این دستگاه تغییر کرد، اما ذخیره در حساب انجام نشد.',
  'language.english':'English','language.persian':'فارسی'
 }
};
const exactMap={
 'Home':'nav.home','Learn':'nav.learn','Speak':'nav.speak','Partners':'nav.partners','Review':'nav.review','Profile':'nav.profile',
 'Log in':'auth.login','Create account':'auth.register','Email':'auth.email','Password':'auth.password','Name':'auth.name','Mobile':'auth.mobile',
 'Learn the language you will actually use.':'auth.hero','Speak through real situations, build your course journey, practice daily and connect with language partners.':'auth.sub',
 'I agree to receive plan-related contact or introductions. Optional.':'auth.consent','Could not connect. Refresh and try again.':'auth.connectError',
 'LEARN':'section.learn','SPEAK':'section.speak','PARTNERS':'section.partners','REVIEW':'section.review','PROFILE & PASSPORT':'section.profile','LIFELINGO PRO':'section.pro',
 'Prepare for real life.':'learn.heading','Courses give structure. Every chapter prepares you for a situation you will actually face.':'learn.sub','No active course yet.':'learn.noCourse','COURSE':'learn.course','Loading lesson…':'learn.loadingLesson','Unsupported lesson type.':'learn.unsupported','Complete the previous lesson first.':'learn.previousFirst',
 'Use your English now.':'speak.heading','Conversation Missions and animated scenarios are a core LifeLingo experience, not an extra.':'speak.sub','FEATURED REAL-LIFE MISSION':'speak.featured','This uses LifeLingo’s existing animated mission engine and voice flow.':'speak.engine','🎙 Start speaking':'speak.start','SCENARIO LIBRARY':'speak.library','Practice the situations you care about.':'speak.practice','DAILY SPEAKING':'speak.daily','Use today’s phrase aloud. Daily practice is available on Free.':'speak.dailySub','🔊 Listen':'speak.listen','Open Daily Surprise':'speak.openDaily','🎙 Speak Now':'speak.now',
 'Practice with real people.':'partners.heading','Discover compatible language partners, keep one active Partner on Free, and continue your conversations here.':'partners.sub','Matching preferences':'partners.preferences','Language Partner':'partners.languagePartner','Find Partner':'partners.find','Find a language Partner':'partners.findLong','Open conversations':'partners.open','HUMAN PRACTICE':'partners.human','Free includes Partner discovery and one active direct Partner.':'partners.free',
 'Bring it back before it fades.':'review.heading','Review is built from what you have completed, not a random quiz list.':'review.sub','Building your review queue…':'review.building','Nothing due right now ✓':'review.none','Complete learning lessons and LifeLingo will create useful review items here.':'review.noneSub','Continue learning':'review.continue','Your answer':'review.answer','✓ Correct':'review.correct','Review now':'review.now','PERSONALIZED REVIEW':'review.personalized','Keep weak items alive.':'review.keepAlive','Unlimited review depth':'review.unlimited',
 'YOUR REAL-LIFE JOURNEY':'home.journey','Your next journey is ready.':'home.nextReady','Continue lesson →':'home.continue','Open Learn →':'home.openLearn','day streak':'home.dayStreak','chapters':'home.chapters','LIFE PASSPORT':'home.passport','View Passport':'home.viewPassport','SPEAK NOW':'home.speakNow','Step into a situation, hear the other person and answer out loud.':'home.speakSub','CONTINUE CHAPTER':'home.continueChapter','Chapter complete ✓':'home.chapterComplete','Review or continue your journey with the next chapter.':'home.chapterReview','Open learning path':'learn.openPath','RECOMMENDED FOR YOU':'home.recommended','Real situations based on your goals':'home.realSituations','YOUR GOALS':'home.goals','Tell LifeLingo why you’re learning':'home.tellGoals','Recommendations and scenario order adapt to your choices. You can change them anytime.':'home.goalsSub','Edit goals':'home.editGoals',
 'DAILY SURPRISE':'daily.title','You showed up today ✓':'daily.done','Open today’s real-life challenge':'daily.open','Free every day · speaking or typing':'daily.free','Practice again':'daily.again','🎙 Speak today':'daily.speak','🎙 Mic':'daily.mic','Check & complete':'daily.complete',
 'Your LifeLingo journey.':'profile.title','Edit Profile':'profile.edit','Partner Preferences':'profile.partnerPrefs','Streak':'profile.streak','Chapters':'profile.chapters','Passport Level':'profile.passportLevel','ACHIEVEMENTS':'profile.achievements','Your milestones':'profile.milestones','Earned':'profile.earned','Keep going':'profile.keepGoing','YOUR PLAN':'profile.plan','THEME':'profile.theme','Make LifeLingo yours':'profile.makeYours','Theme preference is saved with your account.':'profile.themeSaved','ACCOUNT & PRIVACY':'profile.account','Partner discovery uses your language profile and age group. Your mobile number remains private and is not shown to Partners.':'profile.privacy','Log out':'profile.logout','Update your LifeLingo identity, goals and preferences without losing progress.':'profile.editSub','Avatar & profile picture':'profile.avatarPhoto','Choose a LifeLingo avatar or upload your own photo.':'profile.avatarHelp','📷 Upload photo':'profile.upload','Display name':'profile.displayName','Bio':'profile.bio','Native language':'profile.native','Learning language':'profile.learning','Current level':'profile.currentLevel','Target level':'profile.targetLevel','Why are you learning?':'profile.why','Preferred scenarios':'profile.scenarios','Interests':'profile.interests','Age group for Partner safety':'profile.ageSafety','Allow my safe language profile to appear in Partner discovery.':'profile.discoverable','Save Profile':'profile.save',
 'Go further, not just past a paywall.':'pro.heading','Free shows the real product. Pro expands chapters, scenarios, review depth and Partner capacity.':'pro.sub','Write a message…':'chat.write','Send':'chat.send','Report':'common.report','Block':'common.block','Syncing your LifeLingo world…':'status.syncing','Could not sync your account.':'status.syncFailed','Conversation progress synced ✓':'status.progressSynced','System':'common.system','Dark':'common.dark','Light':'common.light','← Back':'common.back','← Profile':'common.profile','← Partners':'nav.partners'
};
const attrMap={'Write a message…':'chat.write','Speak or type the phrase…':'daily.placeholder','Your answer':'review.answer','Choose…':'common.choose'};
let locale=resolveLocal(); let observer=null; let syncing=false;
function normalizeLocale(value){const x=String(value||'').toLowerCase().replace('_','-');return x==='fa'||x.startsWith('fa-')?'fa':'en'}
function resolveLocal(){try{const v=localStorage.getItem(STORAGE_KEY);if(SUPPORTED.includes(v))return v}catch(_){}return normalizeLocale(navigator.language||'en')}
function interpolate(str,params){return String(str).replace(/\{(\w+)\}/g,(_,k)=>params?.[k]??`{${k}}`)}
function t(key,params={}){const fallback=messages.en[key]??key;return interpolate(messages[locale]?.[key]??fallback,params)}
function getLanguage(){return locale}
function isRTL(){return locale==='fa'}
function isEnglishTarget(el){return !!el?.closest?.(ENGLISH_TARGET_SELECTORS.join(','))}
function setDocumentDirection(){document.documentElement.lang=locale;document.documentElement.dir=isRTL()?'rtl':'ltr';document.documentElement.dataset.language=locale}
function translateTextNode(node){if(locale==='en'||!node?.nodeValue||!node.parentElement||isEnglishTarget(node.parentElement))return;const raw=node.nodeValue;const trimmed=raw.trim();if(!trimmed)return;let key=exactMap[trimmed];let translated=key?t(key):null;
 if(!translated){let m=trimmed.match(/^Not quite — answer: (.+)$/);if(m)translated=t('review.notQuite',{answer:m[1]});}
 if(!translated){let m=trimmed.match(/^Free review: up to (\d+) due items\.$/);if(m)translated=t('review.freeLimit',{count:m[1]});}
 if(!translated){let m=trimmed.match(/^Passport Level (\d+) · Progress through situations you can handle in real life\.$/);if(m)translated=t('home.passportProgress',{level:m[1]});}
 if(!translated)return;node.nodeValue=raw.replace(trimmed,translated)}
function translateElement(el){if(!(el instanceof Element))return;if(el.matches('[data-i18n]'))el.textContent=t(el.dataset.i18n);if(el.matches('[data-i18n-placeholder]'))el.setAttribute('placeholder',t(el.dataset.i18nPlaceholder));if(el.matches('[data-i18n-title]'))el.setAttribute('title',t(el.dataset.i18nTitle));if(el.matches('[data-i18n-aria]'))el.setAttribute('aria-label',t(el.dataset.i18nAria));
 if(locale==='fa'&&!isEnglishTarget(el)){['placeholder','title','aria-label'].forEach(attr=>{const val=el.getAttribute(attr);const key=val&&(attrMap[val]||exactMap[val]);if(key)el.setAttribute(attr,t(key))});}
 const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode()))translateTextNode(n)}
function applyTranslations(root=document){setDocumentDirection();const target=root===document?document.body:root;if(target)translateElement(target);ensureLanguageControl();markLearningTargets()}
function markLearningTargets(){document.querySelectorAll('.dailyPhrase').forEach(x=>{x.lang='en';x.dir='ltr';x.dataset.learningTarget='true'});document.querySelectorAll('[data-speak]').forEach(x=>{if(x.textContent&&!exactMap[x.textContent.trim()]){x.lang='en';x.dir='ltr'}});document.querySelectorAll('#lessonBody input').forEach(x=>{x.dir='ltr';x.lang='en'});document.querySelectorAll('.chatMessages [lang="en"],.chatMessages .message-user,.chatMessages .message-partner').forEach(x=>x.dir='auto')}
function persistLocal(next){try{localStorage.setItem(STORAGE_KEY,next)}catch(_){}}
function showToast(message){const el=document.querySelector('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(el._i18nTimer);el._i18nTimer=setTimeout(()=>el.classList.remove('show'),2300)}
async function getRemoteLanguage(){const sb=window.llSupabase;if(!sb)return null;try{const {data:{session}}=await sb.auth.getSession();if(!session)return null;const {data,error}=await sb.rpc('get_unified_profile');if(error)throw error;return SUPPORTED.includes(data?.profile?.preferred_language)?data.profile.preferred_language:null}catch(e){console.warn('[LifeLingo i18n] language read failed',e);return null}}
async function persistRemote(next){const sb=window.llSupabase;if(!sb)return;try{const {data:{session}}=await sb.auth.getSession();if(!session)return;const {error}=await sb.rpc('set_preferred_language',{p_language:next});if(error)throw error;showToast(t('status.languageSaved'))}catch(e){console.warn('[LifeLingo i18n] language save failed',e);showToast(t('status.languageSaveFailed'))}}
async function setLanguage(next,{persist=true,remote=true}={}){next=normalizeLocale(next);if(!SUPPORTED.includes(next))next='en';locale=next;if(persist)persistLocal(next);applyTranslations(document);document.dispatchEvent(new CustomEvent('lifelingo:language-change',{detail:{language:next}}));if(remote)await persistRemote(next);return next}
function ensureLanguageControl(){const root=document.querySelector('#profileRoot');if(!root||root.querySelector('[data-language-settings]'))return;const account=[...root.querySelectorAll('.card')].find(x=>/ACCOUNT & PRIVACY|حساب و حریم خصوصی/.test(x.textContent||''));const card=document.createElement('article');card.className='card languageSettingsCard';card.dataset.languageSettings='true';card.style.marginTop='14px';card.innerHTML=`<div class="sectionHead" style="margin:0 0 12px"><div><div class="eyebrow" data-i18n="profile.language">${t('profile.language')}</div><h2 style="margin:5px 0" data-i18n="profile.languageHeading">${t('profile.languageHeading')}</h2></div><div class="languageSegment" role="group" aria-label="Language"><button type="button" data-language="en">English</button><button type="button" data-language="fa">فارسی</button></div></div><p class="muted" data-i18n="profile.languageHelp">${t('profile.languageHelp')}</p>`;if(account)root.insertBefore(card,account);else root.appendChild(card);card.querySelectorAll('[data-language]').forEach(btn=>{btn.classList.toggle('on',btn.dataset.language===locale);btn.addEventListener('click',()=>setLanguage(btn.dataset.language))})}
function refreshControls(){document.querySelectorAll('[data-language]').forEach(btn=>btn.classList.toggle('on',btn.dataset.language===locale))}
async function resolveAuthenticated(){const local=resolveLocal();locale=local;setDocumentDirection();const remote=await getRemoteLanguage();if(remote&&remote!==locale){locale=remote;persistLocal(remote);applyTranslations(document)}else applyTranslations(document);refreshControls()}
function startObserver(){if(observer)return;observer=new MutationObserver(records=>{if(syncing)return;syncing=true;queueMicrotask(()=>{try{for(const r of records){if(r.type==='characterData')translateTextNode(r.target);for(const n of r.addedNodes){if(n.nodeType===Node.ELEMENT_NODE)translateElement(n);else if(n.nodeType===Node.TEXT_NODE)translateTextNode(n)}}ensureLanguageControl();refreshControls();markLearningTargets()}finally{syncing=false}})});observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label']})}
function boot(){setDocumentDirection();applyTranslations(document);startObserver();if(window.llSupabase)resolveAuthenticated();else window.addEventListener('lifelingo:supabase-ready',resolveAuthenticated,{once:true});document.addEventListener('click',e=>{const btn=e.target.closest('[data-language]');if(btn)refreshControls()});window.llSupabase?.auth?.onAuthStateChange?.((_event,session)=>{if(session)resolveAuthenticated();else{locale=resolveLocal();applyTranslations(document)}})}
window.LifeLingoI18n={t,setLanguage,getLanguage,applyTranslations,isRTL,messages};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();