(()=>{
const $=s=>document.querySelector(s);
const user=()=>{try{return JSON.parse(localStorage.getItem('lifelingo_user')||'null')}catch{return null}};
const key=()=>`lifelingo_social_${String(user()?.email||'guest').toLowerCase()}`;
const avatars=[
{id:0,cat:'girls',trait:'cozy',src:'./assets/4C99D87A-32DC-4B66-B834-F15257487B07.png'},
{id:1,cat:'girls',trait:'artist',src:'./assets/8C662C59-60C5-4AB8-A6D9-728B598D3EAE.png'},
{id:2,cat:'girls',trait:'adventurer',src:'./assets/98B0EBC3-1F87-413C-AB08-C6AB17ACE492.png'},
{id:3,cat:'girls',trait:'nerd',src:'./assets/DA3E874A-7DD6-46E9-828B-3688B43FC385.png'},
{id:4,cat:'girls',trait:'cool',src:'./assets/F131F764-76F2-4E70-8F9A-270F2F64804E.png'},
{id:10,cat:'boys',trait:'artist',src:'./assets/1DCA1D8B-E146-4CFF-9803-F2FEDB77F21B.png'},
{id:11,cat:'boys',trait:'cool',src:'./assets/496DCF3B-187B-4F7A-A5BA-F3DFE6D3DD48.png'},
{id:12,cat:'boys',trait:'cozy',src:'./assets/9BA0896E-6704-42C2-8BEF-1589C15C47A7.png'},
{id:13,cat:'boys',trait:'adventurer',src:'./assets/B71F29C4-CA8E-4590-968A-20A8A1D079B9.png'},
{id:14,cat:'boys',trait:'nerd',src:'./assets/D474CA0C-5506-46D8-9718-CF9DB25E2C73.png'}];
const VERSION=13;
const save=s=>localStorage.setItem(key(),JSON.stringify(s));
const load=()=>{try{return Object.assign({avatar:0,surpriseUsed:false,surpriseGender:null,surpriseVersion:VERSION},JSON.parse(localStorage.getItem(key())||'{}'))}catch{return{avatar:0,surpriseUsed:false,surpriseGender:null,surpriseVersion:VERSION}}};
const displayName=()=>{const u=user()||{};return u.name||u.displayName||u.fullName||(u.email?String(u.email).split('@')[0]:'You')};
const byId=id=>avatars.find(a=>a.id===Number(id))||avatars[0];
const faceStyle=i=>{const a=typeof i==='object'?i:byId(i);return `background-image:url('${a.src}?v=70b39584');background-size:cover;background-position:center;background-repeat:no-repeat;background-color:#0b1120`};
const face=(i,cls='')=>`<span class="ll43Face ${cls}" role="img" aria-label="LifeLingo avatar" style="display:block;overflow:hidden;${faceStyle(i)}"></span>`;
function syncProfileButton(){const b=$('#profileBtn');if(!b||!user())return;const s=load();b.style.cssText+=';width:52px;height:52px;padding:3px;border-radius:50%;overflow:hidden;vertical-align:middle;display:inline-grid;place-items:center';b.innerHTML=s.surpriseUsed?`<span style="display:block;width:100%;height:100%;border-radius:50%;${faceStyle(s.avatar)}"></span>`:'<span style="font-size:23px;font-weight:900;color:#c9a7ff">?</span>'}
function host(){const p=$('#profile');if(!p||!user())return null;let h=$('#ll42Social');if(!h){h=document.createElement('section');h.id='ll42Social';h.className='ll42Social';const a=$('#ll41Retention')||$('#ll41DailyProfile')||p.querySelector('.hub');a?.after(h)}return h}
function render(){const h=host();if(!h)return;const s=load();h.innerHTML=`<div class="ll42SocialTop"><div><div class="ll41Eyebrow">YOUR IDENTITY</div><h3>Your LifeLingo avatar</h3><p>${s.surpriseUsed?'Your one-time avatar has been revealed ✨':'One tap. One chance. One avatar made for you.'}</p></div></div><div data-panel></div>`;avatarPanel(h);syncProfileButton()}
function avatarPanel(h){const s=load();if(!s.surpriseUsed){h.querySelector('[data-panel]').innerHTML=`<div class="llSurpriseIntro"><div class="llSurpriseOrb">✨</div><h3>Ready for your surprise?</h3><p>You can reveal your LifeLingo avatar only once. Choose Girl or Boy, then we pick one completely at random.</p><button class="ll42Share" data-surprise>✨ Surprise me</button></div>`;return}const p=byId(s.avatar);h.querySelector('[data-panel]').innerHTML=`<div class="llSurpriseResult"><div class="llRevealGlow"></div>${face(p.id,'ll43PreviewFace llSurpriseFace')}<div class="llRevealCopy"><small>✨ YOUR LIFELINGO AVATAR ✨</small><h3>${displayName()}, meet your avatar</h3><p>${p.trait.toUpperCase()} ${p.cat==='girls'?'GIRL':'BOY'} · Your one-time random identity.</p><button class="ll42Share" data-share>Share to your story</button></div></div>`}
function askGender(h){h.querySelector('[data-panel]').innerHTML=`<div class="llGenderPick"><div class="llSurpriseOrb">?</div><h3>Pick your avatar group</h3><p>Your avatar will be randomly selected only from the group you choose.</p><div class="llGenderBtns"><button data-gender="girls">Girl</button><button data-gender="boys">Boy</button></div></div>`}
function reveal(g,h){const s=load();if(s.surpriseUsed)return avatarPanel(h);const pool=avatars.filter(a=>a.cat===g),p=pool[Math.floor(Math.random()*pool.length)];s.avatar=p.id;s.surpriseUsed=true;s.surpriseGender=g;save(s);avatarPanel(h);syncProfileButton()}
const inviteUrl=()=>location.origin+location.pathname;
const meta={nerd:['CURIOUS · TECHY · PROBLEM SOLVER','I learn languages like I solve code.'],artist:['CREATIVE · EXPRESSIVE · IMAGINATIVE','Every new word adds color to my world.'],adventurer:['BOLD · CURIOUS · EXPLORER','New language. New places. New stories.'],cool:['CONFIDENT · SOCIAL · FEARLESS','I speak first and figure it out.'],cozy:['CALM · THOUGHTFUL · WARM','Slow progress is still progress.']};
const img=src=>new Promise((ok,no)=>{const i=new Image;i.crossOrigin='anonymous';i.onload=()=>ok(i);i.onerror=no;i.src=src});
function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);c.fill()}
async function storyBlob(){const s=load(),a=byId(s.avatar),[tags,quote]=meta[a.trait],name=displayName().toUpperCase();const cv=document.createElement('canvas');cv.width=1080;cv.height=1920;const c=cv.getContext('2d');let g=c.createLinearGradient(0,0,1080,1920);g.addColorStop(0,'#070a16');g.addColorStop(.52,'#17102d');g.addColorStop(1,'#071c22');c.fillStyle=g;c.fillRect(0,0,1080,1920);c.fillStyle='#9d62ff';c.beginPath();c.arc(900,250,330,0,Math.PI*2);c.fill();c.filter='blur(130px)';c.globalAlpha=.22;c.fill();c.filter='none';c.globalAlpha=1;c.fillStyle='#fff';c.font='900 42px system-ui';c.fillText('LIFELINGO',70,100);c.fillStyle='#bba4df';c.font='700 25px system-ui';c.fillText('MY LANGUAGE IDENTITY',70,145);const av=await img(a.src);const box={x:70,y:225,w:940,h:940},scale=Math.max(box.w/av.width,box.h/av.height),sw=box.w/scale,sh=box.h/scale,sx=(av.width-sw)/2,sy=(av.height-sh)/2;c.save();c.beginPath();c.roundRect(box.x,box.y,box.w,box.h,55);c.clip();c.drawImage(av,sx,sy,sw,sh,box.x,box.y,box.w,box.h);let fade=c.createLinearGradient(0,850,0,1170);fade.addColorStop(0,'#0000');fade.addColorStop(1,'#080b18e8');c.fillStyle=fade;c.fillRect(box.x,800,box.w,365);c.restore();c.fillStyle='#fff';c.font='900 78px system-ui';c.fillText(name.slice(0,18),70,1275);c.fillStyle='#c99aff';c.font='900 44px system-ui';c.fillText(`THE ${a.trait.toUpperCase()} ${a.cat==='girls'?'GIRL':'BOY'}`,70,1340);c.fillStyle='#dce3f2';c.font='700 25px system-ui';c.fillText(tags,70,1395);c.fillStyle='#fff';c.font='600 31px system-ui';c.fillText(`“${quote}”`,70,1470);c.fillStyle='#ffffff0d';roundRect(c,70,1540,940,270,38);c.fillStyle='#fff';c.font='900 35px system-ui';c.fillText('WHAT’S YOUR LIFELINGO IDENTITY?',105,1605);c.fillStyle='#aab4cb';c.font='600 25px system-ui';c.fillText('Reveal yours. Scan to play ✨',105,1650);const qr=await img('https://api.qrserver.com/v1/create-qr-code/?size=220x220&data='+encodeURIComponent(inviteUrl()));c.fillStyle='#fff';roundRect(c,755,1570,205,205,20);c.drawImage(qr,770,1585,175,175);c.fillStyle='#8e9ab5';c.font='600 20px system-ui';c.fillText('lifelingo',105,1760);return new Promise(ok=>cv.toBlob(ok,'image/png',.96))}
function ensurePreviewStyle(){if($('#llStoryPreviewStyle'))return;const st=document.createElement('style');st.id='llStoryPreviewStyle';st.textContent=`.llStoryOverlay{position:fixed;inset:0;z-index:99999;background:#02040bd9;backdrop-filter:blur(16px);display:grid;place-items:center;padding:18px}.llStoryModal{width:min(430px,96vw);max-height:94vh;overflow:auto;border:1px solid #ffffff1f;border-radius:28px;background:#0a0f1d;box-shadow:0 30px 100px #000;padding:16px}.llStoryTop{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.llStoryTop b{font-size:18px}.llStoryClose{border:0;background:#ffffff0d;color:#fff;width:38px;height:38px;border-radius:50%;font-size:20px}.llStoryPreviewImg{width:100%;display:block;border-radius:22px;background:#111}.llStoryActions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.llStoryActions button{padding:13px 12px;border-radius:14px;border:1px solid #ffffff1a;background:#11192b;color:#fff;font-weight:900}.llStoryActions .primary{background:linear-gradient(135deg,#7a3cdf,#a640ef);border-color:#b77cff}`;document.head.appendChild(st)}
async function shareFile(blob){const a=byId(load().avatar),file=new File([blob],`lifelingo-${a.trait}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'My LifeLingo Identity'});return true}return false}
function saveBlob(blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`lifelingo-${byId(load().avatar).trait}.png`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1500)}
async function openStoryPreview(){try{ensurePreviewStyle();const old=$('#llStoryOverlay');if(old)old.remove();const blob=await storyBlob(),url=URL.createObjectURL(blob),wrap=document.createElement('div');wrap.id='llStoryOverlay';wrap.className='llStoryOverlay';wrap.innerHTML=`<div class="llStoryModal"><div class="llStoryTop"><b>Your story card ✨</b><button class="llStoryClose" data-close-story>×</button></div><img class="llStoryPreviewImg" src="${url}" alt="LifeLingo story card"><div class="llStoryActions"><button class="primary" data-share-image>Share image</button><button data-save-image>Save image</button></div></div>`;wrap._storyBlob=blob;wrap._storyUrl=url;document.body.appendChild(wrap)}catch(e){console.error('Story preview failed',e);alert('Could not create your story card. Please try again.')}}
async function click(e){const close=e.target.closest('[data-close-story]');if(close){const o=$('#llStoryOverlay');if(o){URL.revokeObjectURL(o._storyUrl);o.remove()}return}const si=e.target.closest('[data-share-image]');if(si){const o=$('#llStoryOverlay');try{const shared=await shareFile(o._storyBlob);if(!shared)saveBlob(o._storyBlob)}catch(err){if(err?.name!=='AbortError')saveBlob(o._storyBlob)}return}const sv=e.target.closest('[data-save-image]');if(sv){const o=$('#llStoryOverlay');saveBlob(o._storyBlob);return}const h=e.target.closest('#ll42Social');if(!h)return;const b=e.target.closest('button');if(!b)return;if(b.dataset.surprise!==undefined)return askGender(h);if(b.dataset.gender)return reveal(b.dataset.gender,h);if(b.dataset.share!==undefined)return openStoryPreview()}
document.addEventListener('click',click);setTimeout(()=>{render();syncProfileButton()},700);setInterval(()=>{if(user()&&!$('#ll42Social'))render();syncProfileButton()},2500);
})();